### PR TITLE
Acceleration detection pause 

### PR DESCRIPTION
**Pull request by carlosdelamora**
Hello Nathan, 

Here is my suggestion on how to detect a pause. In particular, if we use the absolute value of the sum of the velocities, we can detect when there is no movement, i.e., a pause. For example, I believe now if you move back and forth the app knows is not a pause, and will not show the label. 

You are free to reject the request of course.

### CODE REVIEW

**Comment by nathangitter** [comment]
This is an interesting idea, and I like its simplicity.

However, it doesn't seem to work for me. When I do a quick swipe-up gesture, similar to the gif in the README, half of the time it doesn't detect a pause, and the other half of the time it feels slow.

Are you seeing different results when you run it?

**Comment by carlosdelamora** [comment]
I am always getting a pause, but I do notice that when I move it very slowly and then stop it takes some time for the label pause to appear. The reason is that the conditions for the pause are not met and .changed is not being called because I am no longer moving. I believe all the implementations with velocity will present a similar problem.  I did notice this behavior on your original implementation, and I think that the only way around it is to use a timer. I remember you mentioning something against using a timer, but I do not remember why.

**Comment by nathangitter** [comment]
Yeah, it might be improved by checking for a pause at every frame, not just when the gesture moves. I'm trying to avoid a timer as the primary way of detecting a pause to prevent artificial delays—even a short timer can make the gesture feel too slow.

**Comment by ArtFeel** [comment]
You can try [CADisplayLink](https://developer.apple.com/documentation/quartzcore/cadisplaylink) to check for pause at every frame. It is synchronized with UI refresh rate.

**Pull request closed without merging**
